opt_out_usage
default_platform(:android)

lane :build_debug do
	gradle(task: "assembleDebug")
end

lane :build_release do
	gradle(task: "assembleRelease")
end

lane :publish_to_beta do
  upload_to_play_store(track: 'beta', apk: 'app/build/outputs/apk/release/app-release.apk')
end

lane :promote_beta_to_production do
  upload_to_play_store(track: 'beta', track_promote_to: 'production')
end
