opt_out_usage
default_platform(:android)

lane :build_debug do
	gradle(task: "assembleDebug")
end

lane :build_release do
	gradle(task: "assembleRelease")
end

lane :publish_to_beta do |options|
  upload_to_play_store(track: 'beta', validate_only: true, apk: options[:apk_path], json_key_data: ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON'])
end

lane :promote_beta_to_production do |options|
  upload_to_play_store(track: 'beta', validate_only: true, track_promote_to: 'production', skip_upload_changelogs: true, json_key_data: ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON'])
end
