name: Promote Beta To Production

on: workflow_dispatch

jobs:

  publish:
    name: Promote
    runs-on: ubuntu-20.04
    steps:
    - name: Merge beta branch to production branch
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: beta
        target_branch: production
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout source
      uses: actions/checkout@master
      with:
        ref: production
    - name: Read version name
      run: echo "VERSION_NAME=v$(gradle -q printVersionName)" >> $GITHUB_ENV
    - name: Promote release
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'promote_beta_to_production'
        skip-tracking: 'true'
      env:
        GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON }}
    - name: Add 'google-play-production' git tag
      uses: EndBug/add-and-commit@v5
      with:
        branch: production
        tag: 'google-play-production --force'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add <version number> git tag
      uses: EndBug/add-and-commit@v5
      with:
        branch: production
        tag: '${{ env.VERSION_NAME }} --force'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
