name: Promote Beta To Production

on: workflow_dispatch

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
    - name: Merge beta branch to production branch
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: beta
        target_branch: production
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout Source
      uses: actions/checkout@master
      with:
        ref: production
    - name: Read Version Name
      run: echo "VERSION_NAME=v$(gradle -q printVersionName)" >> $GITHUB_ENV
    - name: Upload release
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'promote_beta_to_production'
        skip-tracking: 'true'
      env:
        GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_API_KEY_JSON }}
    - name: Update Production Git Tag
      uses: richardsimko/update-tag@v1
      with:
        tag_name: google-play-production
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add Version Git Tag
      uses: richardsimko/update-tag@v1
      with:
        tag_name: ${{ env.VERSION_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
